name: Scrape profile

on:
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Retrieve profile
        run: |
          curl 'https://api.bsky.app/xrpc/app.bsky.actor.getProfiles?actors=did:plc:ia76kvnndjutgedggx2ibrem' \
          | jq '.profiles[0] | del(.description)' > profile.json
      - name: Push to repository
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          git add profile.json
          git commit -m "update: $(date --iso-8601=seconds)" || exit 0
          git push
